[tool.poetry]
name = "swervelib"
version = "0.1.0"
description = "Swerve drive library for FRC"
authors = ["Ethan Wall <ewall25@jesuittampa.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "~3.11"
robotpy = {version = "^2023.1.1", extras = ["ctre", "commands2"]}
numpy = "^1.24.1"
Pint = "^0.20.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
